const Constants = {
  /** Key for localstorage */
  Auth: "auth",
  ProjectTypes: [
    { value: "Feature movie (Cinema)" },
    { value: "Short Film" },
    { value: "Feature movie (TV)" },
    { value: "Feature movie (TV, event)" },
    { value: "Feature movie (TV, Series)" },
    { value: "TV Mini Series" },
    { value: "TV Series" },
    { value: "TV Show" },
    { value: "TV Magazine" },
    { value: "TV Report" },
    { value: "Documentary (Cinema)" },
    { value: "Documentary (TV)" },
    { value: "Documentary (Series)" },
    { value: "Documentary (Mini Series)" },
    { value: "Dramatized Documentary" },
    { value: "Commercial" },
    { value: "Corporate Film" },
    { value: "Product Film" },
    { value: "Business Movie" },
    { value: "Recruiting Spot" },
    { value: "Image Film" },
    { value: "Exploratory Film" },
    { value: "Industrial Film" },
    { value: "Video Clip" },
    { value: "Social Media" },
    { value: "Stage Production" },
    { value: "Photography" },
    { value: "Newscast" },
    { value: "Event Film" },
    { value: "Augmented Reality" },
    { value: "Virtual Reality" },
    { value: "Factual " },
    { value: "Infotainment" },
    { value: "Reality" },
    { value: "Scripted Reality" },
  ],
  CoreFunctions: [
    { value: "Production Calendar" },
    { value: "Shooting Scheduling" },
    { value: "Call Sheets" },
    { value: "Financing" },
  ],
  DeptFunctions: [
    { value: "Locations and sets" },
    { value: "Cast " },
    { value: "Costumes" },
    { value: "Hair and makeup" },
    { value: "Production design (cars, props etc)" },
    { value: "Stunts" },
    { value: "Choreography" },
    { value: "Visual Effects" },
    { value: "Marketing" },
  ],
};

export default Constants;
